#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to run.
#
# Note: installs pre-commit git hook to run linters before each commit.

set -e

ROOT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. && pwd )
cd "$ROOT_DIR"

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby…"
  rbenv install --skip-existing
  command -v bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ ! -L "${ROOT_DIR}/.git/hooks/pre-commit" ]; then
    echo "Creating pre-commit hook in .git/hooks/"
    ln -s "${ROOT_DIR}/hooks/pre-commit" "${ROOT_DIR}/.git/hooks/pre-commit"
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies…"
  bundle config set --local path 'vendor/gems'
  bundle install
fi
