#!/bin/bash

#
# Create bare fixture git repos in spec/repo-fixtures by runnning the "build.sh"
# builder script in each repo builder directory in spec/repo-builders.
#

ROOT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. && pwd )

for repo in $(ls ${ROOT_DIR}/spec/repo-fixtures/); do
  if ! [ -d ${ROOT_DIR}/spec/repo-builders/${repo} ]; then
    echo "No builder for ${repo}! Skipping..."
    continue
  fi

  if ! [ -f ${ROOT_DIR}/spec/repo-builders/${repo}/build.sh ]; then
    echo "No build.sh for ${repo}! Skipping..."
    continue
  fi

  echo "Building ${repo}..."

  echo "Removing old repo..."
  cd ${ROOT_DIR}/spec/repo-fixtures/
  rm -rf ${repo}
  mkdir ${repo}
  cd ${repo}
  git init --bare

  echo "Cloning empty bare repo to working dir..."
  cd ${ROOT_DIR}/spec/repo-builders/${repo}
  rm -rf working
  git clone ${ROOT_DIR}/spec/repo-fixtures/${repo} working
  cd working

  echo "Running build.sh for ${repo}..."
  sh ${ROOT_DIR}/spec/repo-builders/${repo}/build.sh

  echo "Pushing to bare repo..."
  git push --all origin
  cd ${ROOT_DIR}/spec/repo-fixtures/${repo}

  echo "Removing working dir..."
  rm -rf ${ROOT_DIR}/spec/repo-builders/${repo}/working
done
