#!/bin/sh

# script/test: run the test suite

set -e

ROOT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. && pwd )
cd "$ROOT_DIR"

# when no arguments passed
if [ $# -eq 0 ]; then
  # run all tests
  bundle exec rake spec
else
  bundle exec ruby -Ilib:spec "$@"
fi
