#!/bin/sh

# script/test: run the test suite

set -e

ROOT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && cd .. && pwd )
cd "$ROOT_DIR"

# run `rake test`
bundle exec rake spec "$@"
