name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-with-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./spec/Dockerfile
          tags: rick/branch-deploy-acceptance:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    depends-on: build-with-docker
    runs-on: rick/branch-deploy-acceptance:latest
    steps:
      - name: Run tests
        run: bundle exec rake

