name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-with-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./spec/Dockerfile
          tags: rick/branch-deploy-acceptance:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run tests
        run: docker run -e -w/app/branch-deploy rick/branch-deploy-acceptance:latest bundle exec rake

